[package]
name = "bbb_webui"
version = "0.2.0"
authors = ["Oleg Antonyan <oleg.b.antonyan@gmail.com>"]

[dependencies]
rocket = "*"
rust-embed = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates", "serve"]

[profile.release]
panic = "abort"
