[package]
name = "bbb_webui"
version = "0.1.0"
authors = ["Oleg Antonyan <oleg.b.antonyan@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]

[profile.release]
panic = "abort"
